global:
  scrape_interval: 15s # Scrape interval for all targets

scrape_configs:
  - job_name: 'dcgm-exporter'
    static_configs:
      - targets:
        - dcgm-exporter:9400
    metrics_path: /metrics

  - job_name: triton-inference-server
    static_configs:
      - targets:
        - triton-inference-server:8002
    metrics_path: /metrics

  - job_name: notebook-app
    static_configs:
      - targets:
        - notebook-app:8000
    metrics_path: /